CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),username VARCHAR(40) UNIQUE NOT NULL,display_name VARCHAR(80) NOT NULL,password_hash TEXT,avatar_url TEXT,bio TEXT,language VARCHAR(10) NOT NULL DEFAULT 'tr',coins BIGINT NOT NULL DEFAULT 0,diamonds BIGINT NOT NULL DEFAULT 0,total_sent_coins BIGINT NOT NULL DEFAULT 0,total_received_diamonds BIGINT NOT NULL DEFAULT 0,coin_level INT NOT NULL DEFAULT 1,gift_level INT NOT NULL DEFAULT 1,is_hidden BOOLEAN NOT NULL DEFAULT FALSE,account_status VARCHAR(20) NOT NULL DEFAULT 'active',system_role VARCHAR(20) NOT NULL DEFAULT 'user',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS rooms(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name VARCHAR(120) NOT NULL,room_type VARCHAR(20) NOT NULL DEFAULT 'audio',seat_count INT NOT NULL DEFAULT 8 CHECK(seat_count IN(2,5,8,9,12,15,20)),owner_id UUID NOT NULL REFERENCES users(id),is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS room_members(room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,user_id UUID REFERENCES users(id) ON DELETE CASCADE,role VARCHAR(20) NOT NULL DEFAULT 'user',microphone BOOLEAN NOT NULL DEFAULT FALSE,seat_index INT,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(room_id,user_id),UNIQUE(room_id,seat_index));
CREATE TABLE IF NOT EXISTS room_blocks(room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,blocked_user_id UUID REFERENCES users(id) ON DELETE CASCADE,blocked_by_user_id UUID REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(room_id,blocked_user_id));
CREATE TABLE IF NOT EXISTS gifts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name VARCHAR(80) NOT NULL,coin_price BIGINT NOT NULL CHECK(coin_price>0),icon_url TEXT,animation_url TEXT,animation_format VARCHAR(20) DEFAULT 'lottie',has_alpha BOOLEAN DEFAULT TRUE,is_active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS gift_transactions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),room_id UUID REFERENCES rooms(id),sender_id UUID REFERENCES users(id),receiver_id UUID REFERENCES users(id),gift_id UUID REFERENCES gifts(id),quantity BIGINT NOT NULL CHECK(quantity>0),coin_amount BIGINT NOT NULL CHECK(coin_amount>0),created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS wallet_transactions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID REFERENCES users(id),transaction_type VARCHAR(50) NOT NULL,coin_amount BIGINT DEFAULT 0,diamond_amount BIGINT DEFAULT 0,reference_id TEXT,description TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS financial_audit_logs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),admin_id UUID REFERENCES users(id),user_id UUID REFERENCES users(id),action VARCHAR(80) NOT NULL,reference_type VARCHAR(50),reference_id TEXT,amount_coins BIGINT DEFAULT 0,amount_diamonds BIGINT DEFAULT 0,balance_before BIGINT,balance_after BIGINT,metadata JSONB,created_at TIMESTAMPTZ DEFAULT NOW());
