name: Flutter APK Derleme

on:
  push:
    branches: [ "main", "ana" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Projeyi Otomatik Bul ve Derle
        run: |
          # Klasör yapısı ne olursa olsun pubspec.yaml dosyasını bulur
          FLUTTER_PATH=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          echo "Proje konumu: $FLUTTER_PATH"
          cd "$FLUTTER_PATH"
          flutter pub get
          flutter build apk --release
          
      - name: APK'yı Çıktı Olarak Paylaş
        uses: actions/upload-artifact@v4
        with:
          name: tr-canli-apk
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
